import Navbar from "@/Components/Navbar";
import type { Metadata } from "next";
import Footer from "@/Components/Footer";
import "./globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="relative ove">
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
